version: "3.9"
services:
  server:
    build:
      dockerfile: server.Dockerfile
      context: .
    environment:
      CONFIG_PATH: config/docker_compose.yaml
    ports:
    - "8080:8080"
  client:
    build:
      dockerfile: client.Dockerfile
      context: .
    depends_on:
      server:
        condition: service_started
    environment:
      CONFIG_PATH: config/docker_compose.yaml

