// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	book "github.com/vladimirpekarski/wordofwisdom/internal/book"
)

// RandomQuoter is an autogenerated mock type for the RandomQuoter type
type RandomQuoter struct {
	mock.Mock
}

// RandomQuote provides a mock function with given fields:
func (_m *RandomQuoter) RandomQuote() book.Record {
	ret := _m.Called()

	var r0 book.Record
	if rf, ok := ret.Get(0).(func() book.Record); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(book.Record)
	}

	return r0
}

type mockConstructorTestingTNewRandomQuoter interface {
	mock.TestingT
	Cleanup(func())
}

// NewRandomQuoter creates a new instance of RandomQuoter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRandomQuoter(t mockConstructorTestingTNewRandomQuoter) *RandomQuoter {
	mock := &RandomQuoter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
